name: newdsl
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sizer: ^3.0.4
  lottie: ^3.1.3
  no_context_navigation: ^3.0.0
  drop_down_search_field: ^1.0.6
  dio: ^5.7.0
  http: ^1.2.2
  provider: ^6.1.2
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
